version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria_db
    links:
      - maria_db:vanEscolar
  maria_db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vanEscolar
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
