openapi: '3.0.2'
info:
  title: SEC_BUS API RESPONSAVEIS
  version: '1.0'
  description: Esta documentação serve para mostrar o fluxo das requisições relacionadas aos responsáveis
servers:
  - url: http://localhost:8080
    
paths:
  
  /responsaveis:
    
  /responsaveis/{id}:
